### ISSUE TITLE
Definir padrões para modelagem de dados

### ISSUE THREAD

**Issue by lucasfusinato** [IBAD-Ibirama/ibad#1]
Deve ser definido um padrão para modelagem de dados, a fim de garantir que os artefatos de banco de dados sejam criados em uma mesma estrutura, independente do módulo ao qual pertencem.

Devem ser previstas, minimamente, as seguintes características:
- SGBD e versão utilizados
- Nomenclatura de tabela
- Nomenclatura de coluna
- Nomenclatura de chave primária
- Nomenclatura de chave estrangeira
- Nomenclatura de constraints

**Comment by lucasfusinato** [comment]
Conforme discussão inicial em sala no dia 03/03/2020 e votação realizada no dia 10/03/2020, o SGBD utilizado para o banco de dados será o [PostgreSQL](https://www.postgresql.org/).

**Comment by JefiPNZ** [comment]
Deixo aqui minhas sugestões para a utilização de uma padronização a seguir. Gostaria de que deixassem suas sugestões:

Nomenclatura de tabela
Sugiro utillizar tbnomedatabela, lowercase, sem underscore.

Nomenclatura de coluna
Sugiro que sejam utilizado lowercase, com underscore, ex: data_de_nascimento ou sem underscore, ex: datadenascimento.

Para nomenclatura de constraints, recomendo utilizar lowercase com underscore:
Sugiro utilizar a nomenclatura pk_tabelaalvo para primary keys, ex: pk_atleta, pk_competicao.
Sugiro que utilizem a nomenclatura fk_tabelaorigem_tabelaalvo para foreign keys, ex: fk_competicao_modalidade para uma fk na tabela de competição que referencia modalidade.
Sugiro a utilização de idx_coluna para índices e ctx_ para outras constraints, ex: idx_nome, ctx_idade_valida

Acredito que seria útil ter ao menos uma tabela de localidades para armazenar ruas, bairros, cidade, estado pois vejo alguns lugares que haverão endereços, e poderia haver a reusabilidade de dados já cadastrados.

**Comment by lucasfusinato** [comment]
Devem ser previstas, minimamente, as seguintes características:

Nomenclatura de tabela
Nomenclatura de coluna
Nomenclatura de chave primária
Nomenclatura de chave estrangeira
Nomenclatura de constraints

**Comment by lucasfusinato** [comment]
Como inicialmente não havia um framework definido para o desenvolvimento, e agora é [provável que iremos utilizar o Laravel](https://github.com/IBAD-Ibirama/ibad/issues/2), sugiro que os padrões de modelagem de dados sigam as convenções especificadas na própria [documentação do Laravel](https://laravel.com/docs/7.x/).

Penso isso principalmente porque a documentação deles é bem completa, assim como a comunidade é bem grande. Em qualquer momento se chegarmos em uma situação imprevista, facilmente conseguiremos saber qual é o padrão que deve ser utilizado apenas buscando no Google ou na documentação do Laravel.


## Nomenclatura de tabela
- Deve ser escrtita no padrão [Snake Case](https://en.wikipedia.org/wiki/Snake_case), separando as palavras por `_`
- O framework assume que as classes de modelo estejam no singular, enquanto as tabelas estejam escritas no plural, sempre acrescentando um `s` no final da palavra
- É possível manualmente definir o nome da tabela de uma classe de modelo quando, por exemplo, apenas acrescentar um `s` não garanta o plural da palavra
- Tabelas de relacionamento N-N podem ser escritas no singular

### Exemplos de nomes de tabela
- usuarios
- atletas
- competicoes
- atleta_competicao

### Referências
- [Eloquent - Getting Started](https://laravel.com/docs/7.x/eloquent), seção **Table Names**
- [Eloquent - Relationships](https://laravel.com/docs/7.x/eloquent-relationships#many-to-many)



## Nomenclatura de chave primária
- O nome padrão das colunas de chave primária das tabelas é `id`
- Não é necessário especificar o nome da constraint de chave primária ao criar a tabela

### Referências
- [Eloquent - Getting Started](https://laravel.com/docs/7.x/eloquent), seção **Primary Keys**



## Nomenclatura de chave estrangeira
- Quando minha tabela possuir uma coluna que é referencia outra tabela, o nmome dessa coluna deve ser `model_id`, onde `model` é o nome da classe referenciada

- Não é necessário especificar o nome da constraint da chave estrangeira ao criar a tabela

### Referências
- [Migrations - Foreign Key Constraints](https://laravel.com/docs/7.x/migrations#foreign-key-constraints)

## Nomenclatura de índice
- São suportados os índices: primary, unique, index, spatialIndex
- Não é necessário especificar o nome do índice ao criar a tabela

### Referências
- [Migrations - Indexes](https://laravel.com/docs/7.x/migrations#indexes)



## Outras constraints
- Não há um suporte nativo para criação de `CHECK CONSTRAINTS`
- Nesse caso há duas soluções, uma seria criar comandos SQL manuais, o que não recomendo pois tiraria todo o objetivo do framework de permitir compatibilidade com vários bancos de dados, e outra seria implementar esse tipo de regra de negócio no próprio código-fonte, que pro nosso caso acredito ser mais interessante
