### ISSUE TITLE
Verificar seeders no ambiente de produção

### ISSUE THREAD

**Issue by lucasfusinato** [IBAD-Ibirama/ibad#14]
Necessário ajustar a classe **DatabaseSeeder** para que não insira informações das tabelas no ambiente de produção.

Um exemplo para corrigir a situação seria fazer uma verificação com base nas variáveis de ambiente, como por exemplo `if(App::environment('local')) {  /* seed */ }`, conforme é descrito na [documentação](https://laravel.com/docs/8.x/configuration#determining-the-current-environment).

Devem ser verificados os seeders abaixo:
- MovesSeeder
- SponsorSeeder
- AthleteSeeder
- TeamSeeder
- TeamAthleteSeeder
- FaultLimitSeeder
- TrainingSeeder

**Comment by GustavoSantosCS** [comment]
Analisando o projeto!
FaultLimitSeeder é algo importante ele gera o limite de faltas padrão do sistema.
Não coloca-lo em produção vai impedir algumas funções de funcionarem.

**Comment by lucasfusinato** [comment]
Resolvido na PR #31.
