### ISSUE TITLE
Utilizar padrões do Laravel para dependências externas no Frontend

### ISSUE THREAD

**Issue by lucasfusinato** [IBAD-Ibirama/ibad#17]
Conforme especifica a [documentação do Laravel](https://laravel.com/docs/7.x/frontend#introduction), o framework já prevê alguns tratamentos para integração com dependências externas, como por exemplo o Bootstrap. Seguindo esses padrões, o Laravel é capaz de compilar todas as dependências em um único arquivo JS e um único arquivo CSS.

Desta forma, poderíamos alterar a implementação do [layout base](https://github.com/IBAD-Ibirama/ibad/blob/master/resources/views/layouts/app.blade.php) para que faça a importação desses arquivos compilados ao invés de referenciar endereços externos, reduzindo a dependência do projeto e até mesmo a quantidade de requisições necessárias para carregar a página no primeiro acesso.

**Comment by jpedroschmitz** [comment]
Feito na #37
