### ISSUE TITLE
Subir aplicação em um servidor

### ISSUE THREAD

**Issue by lucasfusinato** [IBAD-Ibirama/ibad#18]
Para a entrega final do projeto, será necessário subir a aplicação em um servidor online para que o professor consiga utilizá-la.

Uma sugestão seria utilizar o [Heroku](https://www.heroku.com/).

**Comment by jpedroschmitz** [comment]
Creio que podemos fechar a issue, visto que o código da master foi integrado ao Heroku pelo @MarioFronza
