### ISSUE TITLE
Definir padrões para desenvolvimento do back-end

### ISSUE THREAD

**Issue by lucasfusinato** [IBAD-Ibirama/ibad#2]
Deve ser definido um padrão para desenvolvimento do back-end, a fim de garantir que os componentes da aplicação sejam criados em uma mesma estrutura, independente do módulo ao qual pertencem.

Devem ser previstas, minimamente, as seguintes características:
- Linguagem e versão utilizadas
- Arquitetura da aplicação
- Nomenclatura de classe
- Nomenclatura de método
- Nomenclatura de atributo
- Nomenclatura de variável

**Comment by lucasfusinato** [comment]
Conforme discussão inicial em sala no dia 03/03/2020 e votação realizada no dia 10/03/2020, a linguagem utilizada para o back-end será o [PHP](https://www.php.net/manual/pt_BR/).

**Comment by lucasfusinato** [comment]
Sugiro utilizar a versão [7.4.3](https://www.php.net/manual/pt_BR/migration74.new-features.php) do PHP, que é a versão estável atual da linguagem.

**Comment by lucasfusinato** [comment]
Recentemente estive estudando o framework [Laravel](https://laravel.com/), na ideia de desenvolvermos uma [API Rest](https://pt.wikipedia.org/wiki/REST) para acessar os dados. Acredito ser uma opção bem interessante para o back-end, pois irá agilizar muito o desenvolvimento, além de se encaixar bem em alguns [requisitos de qualidade](https://www.devmedia.com.br/qualidade-de-software/9408) como **segurança**, **manutenibilidade** e **portabilidade**.

Abaixo alguns links úteis:

- [REST - Dicionário do Programador](https://www.youtube.com/watch?v=S7MduKwvVGk)
- [Criando uma API Rest com Laravel em 10 minutos](https://www.youtube.com/watch?v=daq5S5-55Lw)
- [Laravel api Tutorial for Beginners Step by Step](https://www.youtube.com/watch?v=rDJ7BebkNso&list=PLYVcyg3AF-zu7zYcRjbxyo0SEYjXmUaTs&index=13)

**Comment by GustavoJung** [comment]
A favor de utilizarmos o Laravel

**Comment by MarioFronza** [comment]
A princípio não estarei efetivamente trabalhando no back-end, mas caso precise ajudar meu voto fica no Laravel por sua padronização e facilidade de aprendizado.

**Comment by gbsoares12** [comment]
Estive dando uma pesquisada sobre o Laravel, me parece que realmente irá nos ajudar bastante no desenvolvimento, principalmente nos pontos citados pelo Fusinato, creio tbm que uma API Rest seja a melhor medida.
