### ISSUE TITLE
FrontEnd: bibliotecas, protótipo e equipe

### ISSUE THREAD

**Issue by jpedroschmitz** [IBAD-Ibirama/ibad#3]
O FrontEnd da aplicação pode ser iniciado independentemente das definições do BackEnd, pois podemos desenvolver tanto o protótipo (já iniciado) como todo o HTML + CSS e JavaScript antes, e só depois repassar ao time do BackEnd para eles implementarem as funcionalidades.

## Bibliotecas

Precisamos definir se vamos usar alguma biblioteca FrontEnd e se sim, qual.

## Protótipo

O protótipo fica de minha responsabilidade, vou terminar ele me baseando no que vocês fizeram semestre passado, se mudou alguma coisa por favor me avisem.

Se quiserem ver um preview, só [clicar aqui](https://www.figma.com/proto/H6tatdWguS0l2W3a3zzVEM/Prot%C3%B3tipo-GPR?node-id=1%3A3&viewport=-30%2C-194%2C0.646136462688446&scaling=min-zoom).

## Equipe

Seria muito interessante que todos participassem, afinal somos uma equipe e saber trabalhar como um time é uma skill muito necessária hoje em dia. Por isso, cada grupo precisa se organizar e definir quem vai trabalhar no FrontEnd. A pessoa responsável precisa responder essa issue, de modo que conseguimos montar o time e reunir a opinião de todos, agilizando assim a tomada de decisão. Segue um exemplo de template para resposta (só copiar, colocar e modificar):

```md
- **Grupo:** Qual o seu grupo? 1, 2, 3, 4 ou 5?
- **Protótipo:** Colocar sugestões de melhoria, se está bom, enfim...
- **Biblioteca:**
  - **Concorda em usar:** Sim/Não
  - **Se não, por que?:** Motivo pelo qual não concorda em usar
  - **Se sim, qual:** Colocar nome e link do site ou repositório e citar motivos da escolha
  - **Observações:** algo a acrescentar sobre o que foi abordado na issue? 
- **Experiência:** qual seu conhecimento de HTML + CSS e JavaScript? Acha bom utilizar jQuery? Sabe fazer layout responsivo? Já usou o Figma para desmontar telas?

Se tiver algo a mais para acresentar, pode colocar aqui.
```

--- 

Uma vez que temos o protótipo pronto e alguns padrões definidos, podemos iniciar o desenvolvimento das telas. Mas até lá vamos abrir uma nova issue aqui para definir responsáveis e como vamos dividir entre a nossa equipe o desenvolvimento das telas.

**Comment by jpedroschmitz** [comment]
- **Grupo:** 1
- **Protótipo:** Como estou fazendo, fico fora dessa 😂 
- **Biblioteca:**
  - **Concorda em usar:** Sim
  - **Se sim, qual:** [Bootstrap](https://getbootstrap.com/) - Acho uma boa utilizar o Bootstrap pois tem muito conteúdo na internet, a curva de aprendizado é rápida e vai agilizar muito o desenvolvimento.
  - **Observações:** Os estilos padrões do Bootstrap são fáceis de perceber em qualquer site, talvez seria interessante modificar um pouco ele, para adaptar ao nosso visual. Fora isso, tudo 100%!
- **Experiência:** Conheço bem HTML + CSS e JavaScript - não acho interessante usar jQuery - sei fazer layouts responsivos - já usei o Figma e sei desmontar telas com ele.

**Comment by GustavoSantosCS** [comment]
- **Grupo:**  2
- **Protótipo:** Não tenho muito a dizer sobre o prototipo até porque tem bem pouco dele ainda, mas o que já tem ta bem legal.
- **Biblioteca:**
  - **Concorda em usar:** Sim
  - **Se sim, qual:** Bootstrap, pelos mesmos motivos que vc falou
  - **Observações:** O bootstrap mais atual já vem com o jQuery "embutido" e é necessário para fazer diversas ações do bootstrap. Então já que ele já esta ai! Bora usar! Ele ajuda bastante a diminuir código JavaScript, sei que a "conversa" entre a lib e o JS vanilla tem que ser bem feita, mas ela pode facilitar muita coisa. Pelo que caminho que o backend ta tomando a gente vai ter que consumir uma Api Rest. Fazer uma requisição ajax no vanilla é foda! Claro que tem libs mais modernas porém nem todo mundo conhece.
- **Experiência:** HTML, CSS, JavaScript e jQuery. Sei fazer layouts responsivos, gosto muito de fazer com o CSS Grid bem simples e poderoso. Nunca usei Figma.

**Comment by MarioFronza** [comment]
- **Grupo**: 1
- **Protótipo**: Por mim este modelo está ótimo, só terminar ele com base nos outros módulos
- **Biblioteca:**
  - **Concorda em usar:** Sim
  - **Se sim, qual:**  Bootstrap, acredito que ele vai facilitar bastante no desenvolvimento das telas, bem como na padronização e responsividade da aplicação.
  - **Observações:** Para mim, se for possível não utilizarmos JQuery melhor. 
- **Experiência:** Conhecimento básico de HTML, CSS e JavaScript para FrontEnd. Não tenho conhecimento em JQuery, e pouco conhecimento em layouts responsivos, apenas com Bootstrap e Material UI. Sem conhecimento em Figma.

**Comment by paulohenriquerodrigues** [comment]
-  **Grupo:** 2
- **Protótipo:** Está ótimo
- **Biblioteca:**
  - **Concorda em usar:** Sim
  - **Se sim, qual:** Bootstrap pela facilidade em aprendizagem e padronização
  - **Observações:**
- **Experiência:**  HTML, CSS, JavaScript e jQuery. Sei fazer layouts responsivos. Nunca usei Figma.

**Comment by Volpe6** [comment]
- **Grupo:** 5
- **Protótipo:** ta bom
- **Biblioteca:**
  - **Concorda em usar:** Sim
  - **Se sim, qual:** Bootstrap por possuir varios exemplos de listas tabelas e menus, e ser fácil de aprender
  - **Observações:** 
- **Experiência:** HTML, CSS, JavaScript, JQuery. Pouco conhecimento em layouts responsivos. Nunca usei Figma

**Comment by lucasfusinato** [comment]
- **Grupo:** 3 e 4
- **Protótipo:** Está ok
- **Biblioteca:**
  - **Concorda em usar:** Sim
  - **Qual:** [Bootstrap](https://getbootstrap.com/docs/4.4/getting-started/introduction/) em virtude da documentação e facilidade de aprendizado
  - **Observações:** Alguns componentes do Bootstrap trabalham em conjunto com o jQuery, portanto `dependendo` dos componentes que serão usados, acredito que este poderá facilitar o desenvolvimento
- **Sugestões:**
  - Verificar que na maioria das telas dos módulos não há muita complexidade, portanto o componente `Modal` do Bootstrap pode ser interessante para abrir as telas de inclusão e alteração dos registros sem que o usuário precise recarregar ou sair da página que está no momento
  - Para que possamos trabalhar de forma paralela, procurar desacoplar ao máximo o desenvolvimento do front-end com o do back-end. Futuramente iremos discutir sobre a integração, mas é quase certo que no back-end será desenvolvida uma [API Rest](https://github.com/IBAD-Ibirama/ibad/issues/2) para o acesso às informações

**Comment by BrunoRech** [comment]
- **Grupo:** 4
- **Protótipo:** Parece algo bom e simples para começarmos, se precisar de mais alterações depois ja teremos uma base de layout
- **Biblioteca:**
  - **Concorda em usar:** Sim
  - **Se sim, qual:** Bootstrap pelo conhecimento da maioria do pessoal e pela usabilidade 
- **Experiência:** Já usei JS, HTML, CSS mas muito pouco Bootstrap, acredito que não vai ser problema
